# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spoa_consensus_character <- function(seq, algorithm, gap_algorithm, match, mismatch, gap_open, gap_extend, gap_open2, gap_extend2) {
    .Call(`_spoar_spoa_consensus_character`, seq, algorithm, gap_algorithm, match, mismatch, gap_open, gap_extend, gap_open2, gap_extend2)
}

spoa_align_character <- function(seq, algorithm, gap_algorithm, match, mismatch, gap_open, gap_extend, gap_open2, gap_extend2) {
    .Call(`_spoar_spoa_align_character`, seq, algorithm, gap_algorithm, match, mismatch, gap_open, gap_extend, gap_open2, gap_extend2)
}

