# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spoa_align_character <- function(seq) {
    .Call(`_spoar_spoa_align_character`, seq)
}

spoa_align_xstringset <- function(seq) {
    .Call(`_spoar_spoa_align_xstringset`, seq)
}

