# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spoa_consensus <- function(seq, algorithm, m, n, g, e, q, c, w) {
    .Call(`_spoar_spoa_consensus`, seq, algorithm, m, n, g, e, q, c, w)
}

spoa_consensus_qual <- function(seq, qual, algorithm, m, n, g, e, q, c, w) {
    .Call(`_spoar_spoa_consensus_qual`, seq, qual, algorithm, m, n, g, e, q, c, w)
}

spoa_align <- function(seq, algorithm, m, n, g, e, q, c, w) {
    .Call(`_spoar_spoa_align`, seq, algorithm, m, n, g, e, q, c, w)
}

spoa_align_qual <- function(seq, qual, algorithm, m, n, g, e, q, c, w) {
    .Call(`_spoar_spoa_align_qual`, seq, qual, algorithm, m, n, g, e, q, c, w)
}

